services:
  guitar-scale:
    build: .
    container_name: guitar-scale
    expose:
      - 80
    networks:
      - traefik-proxy
    restart: unless-stopped

networks:
  traefik-proxy:
    external: true
